apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql01-storage
  namespace: kube-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mysql"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: mysql01
              operator: In
              values:
                - true

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql01-storage
  namespace: kube-storage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
