apiVersion: v1
kind: Service
metadata:
  name: mysql01
  namespace: kube-storage
spec:
  type: NodePort
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql01
